frases = [
    "Disciplina.\nConstancia.\nResultados.",
    "El éxito...\nse construye...\ncada día.",
    "Pequeños pasos.\nGrandes destinos.",
    "Hoy es\nel mejor día\npara empezar.",
    "La motivación\nte arranca.\nEl hábito\nte mantiene.",
    "No pares.\nNunca pares.",
    "Un día más.\nUn paso más.",
    "Tú decides.\nTú actúas.\nTú logras.",
    "El cambio\nempieza hoy.",
    "Constancia\nes poder."
]

# 🔹 30 tareas por categoría
tareas_habitos = [
{"dia":"1","tarea":"Leer 10 páginas"},
{"dia":"2","tarea":"Tomar 2L de agua"},
{"dia":"3","tarea":"No usar el celular al despertar"},
{"dia":"4","tarea":"Dormir antes de las 10pm"},
{"dia":"5","tarea":"Hacer tu cama"},
{"dia":"6","tarea":"Escribir 3 metas"},
{"dia":"7","tarea":"Evitar redes sociales 2h"},
{"dia":"8","tarea":"Comer sin distracciones"},
{"dia":"9","tarea":"Escuchar un podcast"},
{"dia":"10","tarea":"Meditar 5 minutos"},
{"dia":"11","tarea":"Agradecer 3 cosas"},
{"dia":"12","tarea":"No azúcar hoy"},
{"dia":"13","tarea":"Organizar tu espacio"},
{"dia":"14","tarea":"Leer 15 páginas"},
{"dia":"15","tarea":"Despertar temprano"},
{"dia":"16","tarea":"Tomar agua al despertar"},
{"dia":"17","tarea":"No procrastinar 1h"},
{"dia":"18","tarea":"Planear tu día"},
{"dia":"19","tarea":"Aprender algo nuevo"},
{"dia":"20","tarea":"Evitar quejas"},
{"dia":"21","tarea":"Respirar profundo 5 min"},
{"dia":"22","tarea":"No redes en la noche"},
{"dia":"23","tarea":"Comer saludable"},
{"dia":"24","tarea":"Leer 20 páginas"},
{"dia":"25","tarea":"Dormir 8 horas"},
{"dia":"26","tarea":"Beber agua constantemente"},
{"dia":"27","tarea":"Revisar tus metas"},
{"dia":"28","tarea":"No distracciones al estudiar"},
{"dia":"29","tarea":"Ordenar tu habitación"},
{"dia":"30","tarea":"Reflexionar tu progreso"}
]

tareas_dinero = [
{"dia":"1","tarea":"Ahorrar $5.000"},
{"dia":"2","tarea":"No gastar en cosas innecesarias"},
{"dia":"3","tarea":"Anotar todos tus gastos"},
{"dia":"4","tarea":"Buscar una idea de negocio"},
{"dia":"5","tarea":"Ahorrar $10.000"},
{"dia":"6","tarea":"Ver un video de finanzas"},
{"dia":"7","tarea":"No comprar dulces ni antojos"},
{"dia":"8","tarea":"Ahorrar $5.000"},
{"dia":"9","tarea":"Pensar cómo ganar dinero"},
{"dia":"10","tarea":"Leer sobre dinero o inversiones"},
{"dia":"11","tarea":"Ahorrar $15.000"},
{"dia":"12","tarea":"No gastar nada hoy"},
{"dia":"13","tarea":"Vender algo que no uses"},
{"dia":"14","tarea":"Ahorrar $5.000"},
{"dia":"15","tarea":"Aprender sobre inversión"},
{"dia":"16","tarea":"No comprar impulsivamente"},
{"dia":"17","tarea":"Ahorrar $10.000"},
{"dia":"18","tarea":"Revisar tus gastos"},
{"dia":"19","tarea":"Buscar un cliente"},
{"dia":"20","tarea":"Ahorrar $20.000"},
{"dia":"21","tarea":"Ver un podcast de dinero"},
{"dia":"22","tarea":"No gastar en antojos"},
{"dia":"23","tarea":"Ahorrar $5.000"},
{"dia":"24","tarea":"Pensar en un negocio"},
{"dia":"25","tarea":"Ahorrar $15.000"},
{"dia":"26","tarea":"Aprender sobre ventas"},
{"dia":"27","tarea":"No gastar hoy"},
{"dia":"28","tarea":"Ahorrar $10.000"},
{"dia":"29","tarea":"Revisar tu progreso"},
{"dia":"30","tarea":"Crear tu plan financiero"}
]

tareas_ejercicio = [
{"dia":"1","tarea":"20 flexiones"},
{"dia":"2","tarea":"30 sentadillas"},
{"dia":"3","tarea":"Plancha 30 segundos"},
{"dia":"4","tarea":"Correr 1 km"},
{"dia":"5","tarea":"20 abdominales"},
{"dia":"6","tarea":"Saltar cuerda 2 min"},
{"dia":"7","tarea":"30 jumping jacks"},
{"dia":"8","tarea":"25 flexiones"},
{"dia":"9","tarea":"40 sentadillas"},
{"dia":"10","tarea":"Plancha 45 seg"},
{"dia":"11","tarea":"Correr 2 km"},
{"dia":"12","tarea":"30 abdominales"},
{"dia":"13","tarea":"Saltar cuerda 3 min"},
{"dia":"14","tarea":"40 jumping jacks"},
{"dia":"15","tarea":"30 flexiones"},
{"dia":"16","tarea":"50 sentadillas"},
{"dia":"17","tarea":"Plancha 1 min"},
{"dia":"18","tarea":"Correr 3 km"},
{"dia":"19","tarea":"40 abdominales"},
{"dia":"20","tarea":"Saltar cuerda 5 min"},
{"dia":"21","tarea":"50 jumping jacks"},
{"dia":"22","tarea":"35 flexiones"},
{"dia":"23","tarea":"60 sentadillas"},
{"dia":"24","tarea":"Plancha 1:30 min"},
{"dia":"25","tarea":"Correr 4 km"},
{"dia":"26","tarea":"50 abdominales"},
{"dia":"27","tarea":"Saltar cuerda 6 min"},
{"dia":"28","tarea":"60 jumping jacks"},
{"dia":"29","tarea":"40 flexiones"},
{"dia":"30","tarea":"Entrenamiento completo"}
]